#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-prawn-table
Version  : 0.2.2
Release  : 3
URL      : https://rubygems.org/downloads/prawn-table-0.2.2.gem
Source0  : https://rubygems.org/downloads/prawn-table-0.2.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Ruby
BuildRequires : ruby
BuildRequires : rubygem-mocha
BuildRequires : rubygem-pdf-inspector
BuildRequires : rubygem-prawn-manual_builder
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-yard

%description
No detailed description available

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n prawn-table-0.2.2
gem spec %{SOURCE0} -l --ruby > rubygem-prawn-table.gemspec

%build
gem build rubygem-prawn-table.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
prawn-table-0.2.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/prawn-table-0.2.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/GPLv2
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/GPLv3
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/image.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/in_table.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/span_dummy.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/subtable.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/cells.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/column_width_calculator.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/lib/prawn/table/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/contents.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/example_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/basic_block.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/before_rendering_page.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/cell_border_lines.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/cell_borders_and_bg.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/cell_dimensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/cell_text.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/column_widths.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/content_and_subtables.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/creation.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/filtering.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/flow_and_header.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/image_cells.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/position.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/row_colors.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/span.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/style.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/table.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/manual/table/width.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/prawn-table.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/spec/cell_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/spec/extensions/encoding_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/spec/extensions/mocha.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/spec/table/span_dummy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/prawn-table-0.2.2/spec/table_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/prawn-table-0.2.2.gemspec
