#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-prawn-table
Version  : 0.2.2
Release  : 2
URL      : https://rubygems.org/downloads/prawn-table-0.2.2.gem
Source0  : https://rubygems.org/downloads/prawn-table-0.2.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Ruby
BuildRequires : ruby
BuildRequires : rubygem-mocha
BuildRequires : rubygem-pdf-inspector
BuildRequires : rubygem-prawn-manual_builder
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-yard

%description
No detailed description available

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n prawn-table-0.2.2
gem spec %{SOURCE0} -l --ruby > rubygem-prawn-table.gemspec

%build
gem build rubygem-prawn-table.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
prawn-table-0.2.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/prawn-table-0.2.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Document/cell-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Document/make_cell-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Errors/cdesc-Errors.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/cdesc-Image.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/draw_content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/fit%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/image%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/image_height%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/image_width%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/natural_content_height-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/natural_content_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/position%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/scale%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Image/vposition%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/InTable/cdesc-InTable.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/InTable/column-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/InTable/row-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/avg_spanned_min_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/background_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/border_bottom_color%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/border_bottom_width%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/border_right_color%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/border_right_width%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/bottommost%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/cdesc-SpanDummy.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/draw_borders-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/draw_bounded_content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/natural_content_height-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/natural_content_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/padding_bottom%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/padding_right%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/SpanDummy/rightmost%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Subtable/cdesc-Subtable.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Subtable/draw_content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Subtable/max_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Subtable/min_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Subtable/natural_content_height-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Subtable/natural_content_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Subtable/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Subtable/subtable-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Subtable/text_color%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/cdesc-Text.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/draw_content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/font-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/font_style%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/natural_content_height-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/natural_content_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/set_width_constraints-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/styled_width_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/styled_width_of_single_character-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/text_box-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/text_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/with_font-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/Text/with_text_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/avg_spanned_min_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/background_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_bottom_color%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_bottom_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_bottom_line%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_bottom_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_bottom_width%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_bottom_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_color%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_colors%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_colors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_left_color%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_left_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_left_line%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_left_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_left_width%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_left_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_line%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_lines%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_lines-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_right_color%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_right_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_right_line%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_right_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_right_width%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_right_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_top_color%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_top_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_top_line%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_top_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_top_width%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_top_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_width%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_widths%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/border_widths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/borders-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/cdesc-Cell.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/colspan%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/colspan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/content_height-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/content_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/draw-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/draw_background-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/draw_borders-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/draw_bounded_content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/draw_cells-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/draw_content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/dummy_cells-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/height-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/height_ignoring_span-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/make-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/max_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/max_width_ignoring_span-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/min_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/min_width_ignoring_span-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/natural_content_height-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/natural_content_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/padding%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/padding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/padding_bottom%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/padding_bottom-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/padding_left%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/padding_left-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/padding_right%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/padding_right-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/padding_top%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/padding_top-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/relative_x-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/relative_y-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/rowspan%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/rowspan-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/set_width_constraints-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/spanned_content_height-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/spanned_content_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/style-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/width%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/width_ignoring_span-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/x%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/x-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/y%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cell/y-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/aggregate_cell_values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/cdesc-Cells.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/column-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/column_count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/columns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/filter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/fits_on_current_page%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/height-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/height_with_span-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/index_cells-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/max_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/min_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/row-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/row_count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/rows-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/style-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/transform_spec-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Cells/width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/ColumnWidthCalculator/aggregate_cell_values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/ColumnWidthCalculator/cdesc-ColumnWidthCalculator.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/ColumnWidthCalculator/fill_values_if_needed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/ColumnWidthCalculator/has_a_span_dummy%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/ColumnWidthCalculator/natural_widths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/ColumnWidthCalculator/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Interface/cdesc-Interface.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Interface/make_table-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/Interface/table-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/add_header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/add_one_header_row-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/assert_proper_table_data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/before_rendering_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/cdesc-Table.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/cell_style%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/cells-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/column-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/column_length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/column_widths%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/column_widths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/columns-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/draw-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/fits_on_page%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/header_rows-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/height-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/initial_row_on_initial_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/ink_and_draw_cells-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/ink_and_draw_cells_and_start_new_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/ink_cells-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/make_cells-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/natural_column_widths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/natural_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/number_of_header_rows-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/position-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/position_cells-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/row-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/row_colors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/row_heights-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/row_length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/rows-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/set_background_color-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/set_column_widths-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/set_row_heights-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/start_new_page%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/style-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/Table/with_position-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/Prawn/cdesc-Prawn.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-table-0.2.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/COPYING
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/GPLv2
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/GPLv3
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/lib/prawn/table.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/lib/prawn/table/cell.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/image.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/in_table.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/span_dummy.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/subtable.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/lib/prawn/table/cells.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/lib/prawn/table/column_width_calculator.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/lib/prawn/table/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/contents.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/example_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/basic_block.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/before_rendering_page.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/cell_border_lines.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/cell_borders_and_bg.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/cell_dimensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/cell_text.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/column_widths.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/content_and_subtables.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/creation.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/filtering.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/flow_and_header.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/image_cells.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/position.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/row_colors.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/span.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/style.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/table.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/manual/table/width.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/prawn-table.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/spec/cell_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/spec/extensions/encoding_helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/spec/extensions/mocha.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/spec/table/span_dummy_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-table-0.2.2/spec/table_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/prawn-table-0.2.2.gemspec
